//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by musikCube.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ABOUT                       100
#define IDR_HTML_MUSIKPREFSSOUNDDRIVER  103
#define IDD_PROPPAGE_INTERFACE_WORKFLOW 106
#define IDD_PROPPAGE_FILE_ASSOCIATIONS  107
#define IDD_PROPPAGE_SOUND_DRIVER       108
#define IDR_MAINFRAME                   128
#define IDR_musikTYPE                   129
#define IDR_NOWPLAYING_MENU             129
#define IDD_DIALOG2                     131
#define IDD_DYNPLAYLISTEDITOR           131
#define IDI_MUSIK_16                    133
#define IDI_ICON1                       135
#define IDD_FILEDROP                    138
#define IDD_FILEDROPDLG                 138
#define IDD_DROP_FILES_ON_PLAYLIST      138
#define IDD_DIR_SYNC                    140
#define IDD_SYNCHRONIZATION_SETUP       140
#define IDD_EQUALIZER_SETS              141
#define IDR_EQUALIZER_MENU              142
#define IDR_SELECTION_BOX_OPTIONS_MENU  143
#define IDR_SOURCES_MENU                144
#define IDD_NAME_ENTRY                  145
#define IDR_TRAY_MENU                   146
#define IDD_PROPPAGE_MEDIUM             146
#define IDD_PROPPAGE_SOUND_CROSSFADER   146
#define IDD_PROPPAGE_INTERFACE_TRANPARENCY 147
#define IDB_DOWN                        151
#define IDB_BITMAP1                     153
#define IDB_UP                          153
#define IDR_SELECTION_BOX_CONTEXT_MENU  154
#define IDR_PLAYLIST_CONTEXT_MENU       155
#define IDR_MENU1                       156
#define IDR_PLAYLIST_COLUMNS_MENU       156
#define IDI_SONG_PLAYING                157
#define IDI_ICON3                       158
#define IDI_SONG_NOTPLAYING             158
#define IDB_BITMAP3                     160
#define IDB_SONG_NOTPLAYING             160
#define IDD_TAG_PROPERTIES              161
#define IDD_PROPPAGE_TUNAGE             162
#define IDI_ICON2                       166
#define IDI_MUSIK_32                    166
#define IDD_BATCH_TAG                   167
#define IDD_TAG_BATCH_EDIT              167
#define IDD_FILENAME_MASK               168
#define IDD_ADD_NETSTREAM               169
#define IDD_PROPPAGE_AUTOCAPITALIZE     171
#define IDD_DIALOG1                     172
#define IDD_PROPPAGE_INTERFACE_GENERAL  176
#define IDD_RIP                         177
#define IDD_CD_RIPPER                   177
#define IDR_CDRIP_MENU                  178
#define IDD_PROPPAGE_INTERFACE_DEVICES  178
#define IDI_ICON4                       184
#define IDD_PLUGIN_MANAGER              186
#define IDD_PROPPAGE_INTERNET           187
#define IDI_ICON5                       195
#define IDI_MAINFRAME                   195
#define IDR_DROPDEVICE_MENU             196
#define IDD_THEME_EDITOR                197
#define IDI_ICON6                       199
#define IDI_FILEASSOCIATION             199
#define IDD_GLOBAL_HOTKEYS              200
#define IDC_CHECK_STARTUPSCAN           1007
#define IDC_CHECK_STARTUPSCAN2          1008
#define IDC_CHECK_PL_STRIPES            1009
#define IDC_CHECK_STARTUPSCAN3          1009
#define IDC_CHECK_STARTWITHWINDOWS      1009
#define IDC_COMBO1                      1010
#define IDC_CHECK_STARTUPSCAN4          1010
#define IDC_SOUND_DRIVER                1010
#define IDC_DRIVECOMBO                  1010
#define IDC_FOCUSCURSOR                 1010
#define IDC_FOLLOWCURSOR                1010
#define IDC_COMBO2                      1011
#define IDC_SOUND_DEVICE                1011
#define IDC_RATING                      1011
#define IDC_ENCODER                     1011
#define IDC_COMBO3                      1012
#define IDC_SOUND_PLAYBACK_RATE         1012
#define IDC_EDIT1                       1013
#define IDC_NEWSONG                     1013
#define IDC_EDIT2                       1014
#define IDC_FIELDTYPE2                  1014
#define IDC_SOUND_MAX_CHANNELS          1014
#define IDC_PAUSERESUME                 1014
#define IDC_CHECK1                      1015
#define IDC_EDIT4                       1015
#define IDC_STOP                        1015
#define IDC_ARTIST                      1015
#define IDC_CHECK2                      1016
#define IDC_ENABLE_QUERY2               1016
#define IDC_EDIT7                       1016
#define IDC_ALBUM                       1016
#define IDC_BTNNO                       1017
#define IDC_FIELDVARIABLE2              1017
#define IDC_CHECK3                      1017
#define IDC_EDIT5                       1017
#define IDC_EXIT                        1017
#define IDC_SPCUNDR                     1017
#define IDC_USEUTC                      1017
#define IDC_WRITETAGS                   1017
#define IDC_COMMENTS                    1017
#define IDC_SMART_PREVIOUS_CHECK        1017
#define IDC_BUTTON2                     1018
#define IDC_BTNYES                      1018
#define IDC_FIELDSTRING2                1018
#define IDC_CLOSE                       1018
#define IDC_SAVE_ACTIVE_AS_SELECTED     1018
#define IDC_CHECK6                      1018
#define IDC_CANCEL                      1018
#define IDC_USEUTC2                     1018
#define IDC_CLOSETOTRAY                 1018
#define IDC_REMEMBER                    1019
#define IDC_ENABLE_QUERY3               1019
#define IDC_BUTTON4                     1019
#define IDC_LOAD_ACTIVE_FROM_SELECTED   1019
#define IDC_RESET_DEFAULTS              1019
#define IDC_ENBALBUM                    1019
#define IDC_BUTTON_ACTIVECAPTIONTEXT    1019
#define IDC_RADIO1                      1020
#define IDC_RADIO_ADD_PLAYLIST          1020
#define IDC_FIELDTYPE3                  1020
#define IDC_ENBTRACKNUM                 1020
#define IDC_ENBTRACK                    1020
#define IDC_WHOLEPLAYLIST               1020
#define IDC_BUTTON_INACTIVECAPTION      1020
#define IDC_RADIO2                      1021
#define IDC_RADIO_ADD_NOW_PLAYING       1021
#define IDC_FIELDVARIABLE3              1021
#define IDC_ENBRATING                   1021
#define IDC_QUEUESONG                   1021
#define IDC_BUTTON_INACTIVECAPTIONTEXT  1021
#define IDC_RADIO3                      1022
#define IDC_RADIO_ADD_LIBRARY           1022
#define IDC_FIELDSTRING3                1022
#define IDC_ENBGENRE                    1022
#define IDC_HIERARCHIAL                 1022
#define IDC_BUTTON_BTNFACE              1022
#define IDC_ENABLE_QUERY4               1023
#define IDC_ENBYEAR                     1023
#define IDC_BUTTON_BTNTEXT              1023
#define IDC_FIELDTYPE4                  1024
#define IDC_BUTTON_BTNHILIGHT           1024
#define IDC_FIELDVARIABLE4              1025
#define IDC_BUTTON_BTNSHADOW            1025
#define IDC_FIELDSTRING4                1026
#define IDC_BUTTON_LISTCTRL             1026
#define IDC_ENABLE_QUERY5               1027
#define IDC_BUTTON_LISTCTRLTEXT         1027
#define IDC_FIELDTYPE5                  1028
#define IDC_FIELDVARIABLE5              1029
#define IDC_BUTTON_HIGHLIGHT            1029
#define IDC_EDIT6                       1030
#define IDC_FIELDSTRING5                1030
#define IDC_BUTTON_HIGHLIGHTTEXT        1030
#define IDC_ANYALL                      1032
#define IDC_ENABLE_QUERY1               1033
#define IDC_FIELDTYPE1                  1034
#define IDC_FIELDVARIABLE1              1035
#define IDC_FIELDSTRING1                1036
#define IDC_BUTTON1                     1038
#define IDC_ADD                         1038
#define IDC_NEXT                        1038
#define IDC_BUTTON3                     1039
#define IDC_REMOVE                      1039
#define IDC_SAVE_ACTIVE_AS_NEW          1039
#define IDC_PREV                        1039
#define IDC_CONFIGMASKS                 1039
#define IDC_SHOWDEV                     1039
#define IDC_LIST2                       1040
#define IDC_DIRS                        1040
#define IDC_PRESET_BOX                  1040
#define IDC_PRESETBOX                   1040
#define IDC_BUTTON10                    1040
#define IDC_LIST1                       1042
#define IDC_BUTTON5                     1043
#define IDC_DELETE_SEL                  1043
#define IDC_RESCAN                      1043
#define IDC_LIST3                       1043
#define IDC_BUTTON6                     1044
#define IDC_SET_AS_DEFAULT              1044
#define IDC_BUTTON7                     1045
#define IDC_RESET                       1045
#define IDC_PATH                        1045
#define IDC_BUTTON8                     1046
#define IDC_RENAME_SEL                  1046
#define IDC_BUTTON9                     1047
#define IDC_CLOSE_DLG                   1047
#define IDC_IPADDRESS1                  1048
#define IDC_PATH2                       1048
#define IDC_EDIT                        1049
#define IDC_PATH3                       1049
#define IDC_PATH4                       1050
#define IDC_CHECK_ENABLETRAYICON        1051
#define IDC_PATH5                       1051
#define IDC_CHECK4                      1052
#define IDC_PATH6                       1052
#define IDC_EDIT3                       1053
#define IDC_SEEK                        1053
#define IDC_TRACK                       1053
#define IDC_CHECK_ENABLEBALLOONTIPS     1053
#define IDC_CHECK7                      1053
#define IDC_DELETE                      1054
#define IDC_PATH7                       1054
#define IDC_CHECK5                      1055
#define IDC_TUNAGEENABLED               1056
#define IDC_REFRESH                     1056
#define IDC_PATH8                       1056
#define IDC_TUNAGEURLENABLED            1057
#define IDC_OK                          1057
#define IDC_TUNAGEURL                   1058
#define IDC_SETTINGS                    1058
#define IDC_PATH9                       1058
#define IDC_SPIN1                       1059
#define IDC_PATH10                      1059
#define IDC_TUNAGEFILENAME              1060
#define IDC_BITRATE                     1060
#define IDC_TUNAGEFILEENABLED           1061
#define IDC_DURATION                    1061
#define IDC_TUNAGEFILELINE              1062
#define IDC_FORMAT                      1062
#define IDC_TUNAGEAPPEND                1063
#define IDC_TIMEADDED                   1063
#define IDC_TUNAGECOMMANDLINE           1064
#define IDC_LASTPLAYED                  1064
#define IDC_RUNAPPENABLED               1065
#define IDC_TUNAGERUNAPPENABLED         1065
#define IDC_TIMESPLAYED                 1065
#define IDC_FILENAME                    1066
#define IDC_TITLE                       1067
#define IDC_GENRE                       1068
#define IDC_YEAR                        1069
#define IDC_APPLY                       1070
#define IDC_COMMENT                     1070
#define IDC_ENBTITLE                    1071
#define IDC_ENBARTIST                   1072
#define IDC_MASK                        1073
#define IDC_ENBCOMMENT                  1073
#define IDC_TYPE                        1074
#define IDC_HOTKEY1                     1075
#define IDC_PLAYPAUSE_HOTKEY            1075
#define IDC_NETSTREAM_ADDR              1076
#define IDC_PLAYNOW                     1077
#define IDC_NETSTREAM_ADDR2             1077
#define IDC_NETSTREAM_TITLE             1077
#define IDSTOP                          1078
#define IDSNOOZE                        1079
#define IDC_STOP_HOTKEY                 1081
#define IDC_TIME                        1082
#define IDC_ALARMTIME                   1082
#define IDC_NEXTTRACK_HOTKEY            1082
#define IDC_ALARMDATE                   1083
#define IDC_PREVTRACK_HOTKEY            1085
#define IDC_NAME                        1086
#define IDC_VOLUMEUP_HOTKEY             1086
#define IDC_QUERY                       1087
#define IDC_INSTRUCTIONS                1088
#define IDC_RADIO4                      1089
#define IDC_SLOPPY                      1089
#define IDC_RADIO_USEDARKICONS          1089
#define IDC_RADIO_USELIGHTICONS2        1090
#define IDC_RADIO_USELIGHTICONS         1090
#define IDC_USEGLOBALKEYS               1091
#define IDC_VOLUMEDOWN_HOTKEY           1092
#define IDC_NEXTARTIST_HOTKEY           1093
#define IDC_PROGRESS1                   1094
#define IDC_PREVARTIST_HOTKEY           1094
#define IDC_PROGRESS2                   1095
#define IDC_NEXTALBUM_HOTKEY            1095
#define IDC_SLIDER1                     1096
#define IDC_PREVALBUM_HOTKEY            1096
#define IDC_SLIDERTXT                   1100
#define IDC_SLIDERVAL                   1101
#define IDC_BROWSEFOLDER                1102
#define IDC_BTN_EDITTRACK               1103
#define IDC_BTN_EDITALBUM               1104
#define IDC_STATIC_CURRTRACK            1105
#define IDC_STATIC_OVERALLPERCENT       1106
#define IDC_HIDEDEV                     1108
#define IDC_ABOUTINFO                   1109
#define IDC_CONFIGURE                   1110
#define IDC_EXECUTE                     1111
#define IDC_DESCRIPTION                 1112
#define IDC_PLUGINS                     1113
#define IDC_ABOUT                       1114
#define IDC_SNDBUFFER                   1115
#define IDC_DESCRIPTION2                1115
#define IDC_EDITBOX                     1116
#define IDC_MAINFRAMEICON               1117
#define IDC_FREEDBSERVER                1118
#define IDC_CUBEVER                     1119
#define IDC_SQLITEVER                   1120
#define IDC_TAGLIBVER                   1121
#define IDC_OPENTHREADSVER              1122
#define IDC_OPENTHREADSVER2             1123
#define IDC_BASSVER                     1123
#define IDC_STATIC_TIMEPLAYED           1123
#define IDC_BUTTON_ACTIVECAPTION        1126
#define IDC_BUTTON_LOAD                 1127
#define IDC_BUTTON_SAVE                 1128
#define IDC_CHECK_USEMCEKEYS            1129
#define IDC_CHECK_USEWMEDIAKEYS         1129
#define IDC_EXTENSION_LIST              1129
#define IDC_GLOBALHOTKEYS_BUTTON        1130
#define IDC_HOTKEYS_OK_BUTTON           1131
#define IDC_CANCEL_HOTKEYS_CANCEL_BUTTON 1132
#define IDC_ENABLEHOTKEYS_CHECKBOX      1133
#define IDC_VOLUMEKEYS_CONTROL_MUSIKCUBE_VOL_CHECKBOX 1134
#define ID_FILE_PREFERENCES             32771
#define ID_FILE_SEP                     32772
#define ID_ADD_FILES                    32774
#define ID_ADD_DIRECTORY                32775
#define ID_OPEN_MANAGEDIRECTORIES       32776
#define ID_AUDIO_PLAYBACKMODE           32780
#define ID_PLAYBACKMODE_NORMAL          32781
#define ID_PLAYBACKMODE_REPEAT          32782
#define ID_PLAYBACKMODE_SHUFFLE         32783
#define ID_AUDIO_CROSSFADERENABLED      32784
#define ID_AUDIO_CROSSFADER             32786
#define ID_CROSSFADER_ENABLED           32787
#define ID_CROSSFADER_SETUP             32788
#define ID_AUDIO_EQUALIZER              32789
#define ID_EQUALIZER_ENABLED            32790
#define ID_EQUALIZER_SETUP              32791
#define ID_VIEW_CROSSFADER              32792
#define ID_VIEW_EQUALIZER               32793
#define ID_VIEW_SOURCES                 32794
#define ID_VIEW_NOWPLAYING              32795
#define ID_VIEW_SELECTIONAREA           32796
#define ID_AUDIO_EQUALIZER_ENABLED      32800
#define ID_AUDIO_CROSSFADER_ENABLED     32801
#define ID_PLAYBACKMODE_REPEATSINGLE    32802
#define ID_PLAYBACKMODE_REPEATPLAYLIST  32803
#define ID_PLAYBACKMODE_SHUFFLE32804    32804
#define ID_PLAYBACKMODE_SHUFFLECURRENTPLAYLIST 32805
#define ID_PLAYBACKMODE_INTRO           32807
#define ID_VIEW_PLAYLISTINFORMATION     32814
#define ID_FILE_UNSYNCHRONIZEDTAGS      32817
#define ID_VIEWMODIFIEDTAGS_VIEW        32818
#define ID_UNSYNCHRONIZEDTAGS_WRITETOFILE 32819
#define ID_UNSYNCHRONIZEDTAGS_FINALIZEFORDATABASEONLY 32820
#define ID_FILE_SYNCHRONIZEDDIRECTORIES 32826
#define ID_DISPLAY_LOCKCHANNELS         32831
#define ID_EQUALIZER_PRESETS            32832
#define ID_EQUALIZER_LOCKCHANNELS       32833
#define ID_SELECTIONBOX_CHANGETYPE      32834
#define ID_SELECTIONBOX_RENAME          32835
#define ID_CHANGETYPE_ARTIST            32836
#define ID_CHANGETYPE_ALBUM             32837
#define ID_CHANGETYPE_YEAR              32838
#define ID_CHANGETYPE_GENRE             32839
#define ID_CHANGETYPE_TITLE             32840
#define ID_CHANGETYPE_TRACKNUMBER       32841
#define ID_CHANGETYPE_TIMEADDED         32842
#define ID_CHANGETYPE_LASTPLAYED        32843
#define ID_CHANGETYPE_FILESIZE          32844
#define ID_CHANGETYPE_FORMAT            32845
#define ID_CHANGETYPE_DURATION          32846
#define ID_CHANGETYPE_RATING            32847
#define ID_CHANGETYPE_TIMESPLAYED       32848
#define ID_CHANGETYPE_BITRATE           32849
#define ID_CHANGETYPE_EQUALIZER         32850
#define ID_SOURCES_RENAME               32851
#define ID_Menu                         32852
#define ID_SOURCES_DELETE               32853
#define ID_Menu32854                    32854
#define ID_SOURCES_EDITQUERY            32855
#define ID_Menu32860                    32860
#define ID_EQUALIZER_SET_AS_DEFAULT     32861
#define ID_EQUALIZER_STATE_18BAND       32862
#define ID_EQUALIZER_STATE_9BAND        32863
#define ID_EQUALIZER_STATE_6BAND        32864
#define ID_EQUALIZER_RESETDEFAULT       32866
#define ID_VIEW_RESETINTERFACETODEFAULT 32867
#define ID_NOTIFICATIONTRAY_RESTORE     32868
#define ID_NOTIFICATIONTRAY_PLAY        32869
#define ID_NOTIFICATIONTRAY_PAUSE       32870
#define ID_NOTIFICATIONTRAY_NEXT        32871
#define ID_NOTIFICATIONTRAY_PREV        32872
#define ID_NOTIFICATIONTRAY_STOP        32873
#define ID_NOTIFICATIONTRAY_EXIT        32874
#define ID_NOTIFICATIONTRAY_MUSIK       32875
#define ID_EQUALIZER_REMEMBERPERSONG    32876
#define ID_EQUALIZER_ENABLED2           32880
#define ID_SELECTIONBOX_ADDVIEW         32881
#define ID_SELECTIONBOX_CLOSEVIEW       32882
#define ID_FILE_CLEARLIBRARY            32883
#define ID_SYNCHRONIZATION_UNSYNCHRONIZEDTAGS 32886
#define ID_FILE_LIBRARY                 32887
#define ID_LIBRARY_SYNCHRONIZEDIRECTORIESNOW 32888
#define ID_LIBRARY_SCANFORMISSINGFILESNOW 32889
#define ID_EQUALIZER_CLOSE_VIEW         32891
#define ID_SELECTIONBOXCONTEXT_RENAME   32892
#define ID_SOURCES_SHUFFLEPLAYLIST      32893
#define ID_Menu32894                    32894
#define ID_SELECTIONBOXCONTEXT_DELETE   32897
#define ID_DELETE_FROMLIBRARY           32898
#define ID_DELETE_FROMCOMPUTER          32899
#define ID_PLAYLISTCONTEXTMENU_DELETE   32900
#define ID_PLAYLISTCONTEXTMENU_PROPERTIES 32903
#define ID_PLC_DELETE_FROMLIBRARY       32905
#define ID_PLC_DELETE_FROMPLAYLIST      32906
#define ID_PLC_DELETE_FROMCOMPUTER      32907
#define ID_PLAYLISTCOLUMNS_ARTIST       32908
#define ID_PLAYLISTCOLUMNS_ALBUM        32909
#define ID_PLAYLISTCOLUMNS_YEAR         32910
#define ID_PLAYLISTCOLUMNS_GENRE        32911
#define ID_PLAYLISTCOLUMNS_TITLE        32912
#define ID_PLAYLISTCOLUMNS_TRACKNUMBER  32913
#define ID_PLAYLISTCOLUMNS_TIMEADDED    32914
#define ID_PLAYLISTCOLUMNS_LASTPLAYED   32915
#define ID_PLAYLISTCOLUMNS_FILESIZE     32916
#define ID_PLAYLISTCOLUMNS_FORMAT       32917
#define ID_PLAYLISTCOLUMNS_DURATION     32918
#define ID_PLAYLISTCOLUMNS_RATING       32919
#define ID_PLAYLISTCOLUMNS_TIMESPLAYED  32920
#define ID_PLAYLISTCOLUMNS_BITRATE      32921
#define ID_PLAYLISTCOLUMNS_FILENAME     32922
#define ID_PLAYLISTCONTEXTMENU_SHUFFLENOWPLAYING 32923
#define ID_HELP_VERSION                 32924
#define ID_HELP_CORE                    32925
#define ID_SOURCES_SHOW                 32926
#define ID_SHOW_SUBLIBRARIES            32927
#define ID_SHOW_PLAYLISTS               32928
#define ID_SHOW_SEARCH                  32931
#define ID_VIEW_VISUALIZATION           32932
#define ID_VIEW_ALWAYSONTOP             32935
#define ID_VIEW_FULLSCREEN              32936
#define ID_VIEW_WINAMPVISUALIZATIONS    32939
#define ID_WINAMPVISUALIZATIONS_CONFIGURE 32940
#define ID_WINAMPVISUALIZATIONS_ENABLED 32941
#define ID_WINAMPVISUALIZATIONS_ACTIVATE 32942
#define ID_PLAYLISTCONTEXTMENU_RENAME   32943
#define ID_RENAME_TITLE                 32944
#define ID_RENAME_ARTIST                32945
#define ID_RENAME_ALBUM                 32946
#define ID_RENAME_TRACKNUMBER           32947
#define ID_RENAME_GENRE                 32948
#define ID_RENAME_YEAR                  32949
#define ID_RENAME_RATING                32950
#define ID_Menu32951                    32951
#define ID_PLAYLISTCONTEXTMENU_BATCH    32952
#define ID_PLAYLISTCONTEXTMENU_FILENAME 32953
#define ID_FILENAME_FILENAMEFROMTAG     32954
#define ID_FILENAME_TAGTOFILENAME       32955
#define ID_FILENAME_CONFIGUREMASKS      32956
#define ID_FILENAME_TAGFROMFILENAME     32957
#define ID_ADD_NETSTREAM                32958
#define ID_PLAYLISTCONTEXTMENU_TAGTOLOWERCASE 32962
#define ID_PLAYLISTCONTEXTMENU_TAGTOUPPERCASE 32963
#define ID_PLAYLISTCONTEXTMENU_TAG      32964
#define ID_TAG_AUTOCAPITALIZE           32965
#define ID_SOURCES_SETALARM             32966
#define ID_SHOW_DYNAMICPLAYLISTS        32967
#define ID_RANDOM_PLAYRANDOM            32969
#define ID_PLAYRANDOM_ARTIST            32970
#define ID_PLAYRANDOM_ALBUM             32971
#define ID_PLAYRANDOM_GENRE             32972
#define ID_PLAYRANDOM_YEAR              32973
#define ID_RANDOM_APPENDNOWPLAYING      32974
#define ID_RANDOM_SETASNOWPLAYING       32975
#define ID_RANDOM_QUEUERANDOM           32976
#define ID_QUEUERANDOM_ARTIST           32977
#define ID_QUEUERANDOM_ALBUM            32978
#define ID_QUEUERANDOM_YEAR             32979
#define ID_QUEUERANDOM_GENRE            32980
#define ID_PLAYLISTCONTEXTMENU_RATE     32981
#define ID_RATE_UNRATED                 32983
#define ID_RATE_1                       32984
#define ID_RATE_2                       32985
#define ID_RATE_3                       32986
#define ID_RATE_4                       32987
#define ID_RATE_5                       32988
#define ID_RATE_N1                      32989
#define ID_NOTIFICATIONTRAY_RATECURRENT 32990
#define ID_RATECURRENT_UNRATED          32992
#define ID_RATECURRENT_1                32993
#define ID_RATECURRENT_3                32994
#define ID_RATECURRENT_4                32996
#define ID_RATECURRENT_5                32997
#define ID_RATECURRENT_N1               32998
#define ID_RATECURRENT_2                32999
#define ID_Menu33000                    33000
#define ID_EQUALIZER_USE_GLOBAL         33002
#define ID_SOURCES_COPYTO               33003
#define ID_FILE_RIPCD                   33004
#define ID_CDRIP_EDITALBUMINFO          33005
#define ID_CDRIP_EDITTRACKINFO          33006
#define ID_SOURCES_QUERYFREEDB          33008
#define ID_FILE_OPENLIBRARY             33009
#define ID_FILE_EXPORTLIBRARY           33010
#define ID_FILE_ADVANCED                33011
#define ID_LIBRARY_NEW                  33012
#define ID_LIBRARY_ADVANCED             33013
#define ID_TAG_CLEAN                    33014
#define ID_Menu33015                    33015
#define ID_FILE_ATTEMPTTOSANITISETAGS   33016
#define ID_Menu33017                    33017
#define ID_HELP_UNICODE                 33018
#define ID_Menu33019                    33019
#define ID_SOURCES_RIPCD                33020
#define ID_SOURCES_REFRESHCD            33021
#define ID_PLAYBACK_RANDOM              33022
#define ID_SOURCES_REFRESHDEVICES       33023
#define ID_SOURCES_REMOVABLEDEVICES     33024
#define ID_REMOVABLEDEVICES_RESCANSYSTEM 33025
#define ID_REMOVABLEDEVICES_RELOADDATABASE 33026
#define ID_FILE_RESCANREMOVABLEDEVICES  33027
#define ID_SHOW_DRIVES                  33029
#define ID_FILE_CDRIPPER                33033
#define ID_SOURCES_CREATESTOCK          33035
#define ID_PLAYLISTCONTEXTMENU_RELOADTAGSFROMFILE 33036
#define ID_PLAYLISTCOLUMNS_COMMENTS     33037
#define ID_SOURCES_MOVEUP               33038
#define ID_SOURCES_MOVEDOWN             33039
#define ID_TAGS_REMOVEEXTRAWHITESPACE   33040
#define ID_SOURCES_CLEAR                33041
#define ID_PLAYLISTCONTEXTMENU_REMOVEWHITESPACE 33042
#define ID_TAGS_AUTO                    33043
#define ID_Menu33044                    33044
#define ID_TAGS_ALLTAGS                 33045
#define ID_TAGS_MODIFIEDTAGS            33046
#define ID_FILE_PLUGINMANAGER           33047
#define ID_SELECTIONBOXCONTEXT_PLAYSELECTED 33050
#define ID_SELECTIONBOXCONTEXT_QUEUESELECTED 33051
#define ID_PLAYLISTCONTEXTMENU_QUEUESELECTEDINNOWPLAYING 33052
#define ID_SOURCES_MOVEFILESTO          33053
#define ID_SHOW_PLUGINS                 33054
#define ID_SOURCES_PLUGINEXECUTE        33059
#define ID_SOURCES_PLUGINCONFIGURE      33060
#define ID_SOURCES_PLUGINSTOP           33061
#define ID_SOURCES_PLUGINABOUT          33062
#define ID_SOURCES_SHOWALLSONGS         33074
#define ID_SOURCES_SYNCHRONIZE          33075
#define ID_PLAYLISTCONTEXTMENU_REWRITETAGSTOFILE 33076
#define ID_PLAYLISTCONTEXTMENU_PLAYBACK 33077
#define ID_PLAYLISTCONTEXTMENU_TAGS     33078
#define ID_PLAYLISTCONTEXTMENU_PLAYSELECTED 33079
#define ID_Menu33080                    33080
#define ID_SOURCES_CLEARCOLLECTED       33081
#define ID_PLAYLISTCONTEXTMENU_PLAYNEXT 33083
#define ID_PLAYLISTCONTEXTMENU_REPLACENOWPLAYING 33084
#define ID_PLAYLISTCONTEXTMENU_SHOWINEXPLORER 33085
#define ID_SELECTIONBOXCONTEXT_PLAYNEXT 33086
#define ID_SELECTIONBOXCONTEXT_REPLACENOWPLAYING 33087
#define ID_PLAYLISTCONTEXTMENU_PLAYBACK33088 33088
#define ID_SELECTIONBOXCONTEXT_PLAYBACK 33090
#define ID_PLAYLISTCONTEXTMENU_REPLACENOWPLAYINGANDPLAY 33093
#define ID_SELECTIONBOXCONTEXT_REPLACENOWPLAYINGANDPLAY 33094
#define ID_HELP_ONLINEHELP              33095
#define ID_FILE_IMPORTPLAYLIST          33096
#define ID_FILE_EXPORTPLAYLIST          33097
#define ID_DROPDEVICE_COPYFILESTODEVICE 33100
#define ID_DROPDEVICE_ADDTODEVICE       33101
#define ID_SOURCES_VISIBLE              33102
#define ID_SOURCES_SHOWDEVICES          33103
#define ID_SOURCES_SHOWPLAYLISTS        33104
#define ID_SOURCES_SHOWDYNAMICPLAYLISTS 33105
#define ID_SOURCES_SHOWPLUGINS          33106
#define ID_VIEW_SOURCES33107            33107
#define ID_FILE_THEMEEDITOR             33109
#define ID_VIEW_SELECTIONBOXES          33113
#define ID_FILE_SETTINGS                33116
#define ID_Menu33117                    33117
#define ID_FILE_SELECTEDLIBRARY         33118
#define ID_SOURCES_SYNCHRONIZEDPATHS    33119
#define ID_SOURCES_UNMOUNT              33120
#define ID_MUSICLIBRARY_CHANGE          33121
#define ID_HELP_CHECKFORUPDATES         33122
#define ID_TOOLTIP_EQL1                 61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         33123
#define _APS_NEXT_CONTROL_VALUE         1135
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
